(source gnu)
(source melpa)

;; (package-file "xen.el")
(package "xen" "0.0.1" "Xen's custom stuff.")

(depends-on "company")
(depends-on "flycheck")
(depends-on "php-mode")
(depends-on "projectile")
(depends-on "smartparens")
(depends-on "swiper")

(development
 (depends-on "ecukes")
 (depends-on "el-mock")
 (depends-on "ert-runner")
 (depends-on "espuds")
 (depends-on "f")
 (depends-on "shut-up")
 (depends-on "undercover"))
