(source gnu)
(source melpa)

;; (package-file "xen.el")
(package "xen" "0.0.1" "Xen's custom stuff.")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "espuds")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "php-mode")
 (depends-on "smartparens")
 )
